// <auto-generated />
using System;
using LdprActivistDemo.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace LdprActivistDemo.Migrations.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260306105509_CascadeDeleteRegionCities")]
    partial class CascadeDeleteRegionCities
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("LdprActivistDemo.Persistence.City", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("RegionId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("RegionId", "Name")
                        .IsUnique();

                    b.ToTable("cities", (string)null);
                });

            modelBuilder.Entity("LdprActivistDemo.Persistence.ImageEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<byte[]>("Data")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.HasKey("Id");

                    b.ToTable("images", (string)null);
                });

            modelBuilder.Entity("LdprActivistDemo.Persistence.Region", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("regions", (string)null);
                });

            modelBuilder.Entity("LdprActivistDemo.Persistence.TaskEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AuthorUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("AutoVerificationActionType")
                        .HasColumnType("text");

                    b.Property<int?>("CityId")
                        .HasColumnType("integer");

                    b.Property<Guid?>("CoverImageId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("DeadlineAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ExecutionLocation")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("PublishedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("RegionId")
                        .HasColumnType("integer");

                    b.Property<string>("RequirementsText")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ReuseType")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("disposable");

                    b.Property<int>("RewardPoints")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("VerificationType")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("manual");

                    b.HasKey("Id");

                    b.HasIndex("AuthorUserId");

                    b.HasIndex("CityId");

                    b.HasIndex("CoverImageId");

                    b.HasIndex("RegionId", "CityId", "Status", "DeadlineAt");

                    b.ToTable("tasks", null, t =>
                        {
                            t.HasCheckConstraint("ck_tasks_auto_verification_action_type_allowed", "(\"VerificationType\" = 'manual' AND \"AutoVerificationActionType\" IS NULL) OR (\"VerificationType\" = 'auto' AND \"AutoVerificationActionType\" IN ('invite_friend'))");

                            t.HasCheckConstraint("ck_tasks_reuse_type_allowed", "\"ReuseType\" IN ('disposable','reusable')");

                            t.HasCheckConstraint("ck_tasks_reward_non_negative", "\"RewardPoints\" >= 0");

                            t.HasCheckConstraint("ck_tasks_status_allowed", "\"Status\" IN ('open','closed')");

                            t.HasCheckConstraint("ck_tasks_verification_type_allowed", "\"VerificationType\" IN ('auto','manual')");
                        });
                });

            modelBuilder.Entity("LdprActivistDemo.Persistence.TaskSubmission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("DecidedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("DecidedByAdminId")
                        .HasColumnType("uuid");

                    b.Property<string>("DecisionStatus")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("in_progress");

                    b.Property<string>("ProofText")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("SubmittedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("TaskId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("DecidedByAdminId");

                    b.HasIndex("UserId");

                    b.HasIndex("TaskId", "UserId");

                    b.ToTable("task_submissions", null, t =>
                        {
                            t.HasCheckConstraint("ck_task_submissions_decision_status_allowed", "\"DecisionStatus\" IN ('in_progress','submitted_for_review','approve','rejected')");
                        });
                });

            modelBuilder.Entity("LdprActivistDemo.Persistence.TaskSubmissionImage", b =>
                {
                    b.Property<Guid>("SubmissionId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ImageId")
                        .HasColumnType("uuid");

                    b.HasKey("SubmissionId", "ImageId");

                    b.HasIndex("ImageId");

                    b.ToTable("task_submission_images", (string)null);
                });

            modelBuilder.Entity("LdprActivistDemo.Persistence.TaskTrustedAdmin", b =>
                {
                    b.Property<Guid>("TaskId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("AdminUserId")
                        .HasColumnType("uuid");

                    b.HasKey("TaskId", "AdminUserId");

                    b.HasIndex("AdminUserId");

                    b.ToTable("task_trusted_admins", (string)null);
                });

            modelBuilder.Entity("LdprActivistDemo.Persistence.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AvatarImageUrl")
                        .HasColumnType("text");

                    b.Property<DateOnly>("BirthDate")
                        .HasColumnType("date");

                    b.Property<int>("CityId")
                        .HasColumnType("integer");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Gender")
                        .HasColumnType("text");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsPhoneConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("MiddleName")
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("RegionId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CityId");

                    b.HasIndex("PhoneNumber")
                        .IsUnique();

                    b.HasIndex("RegionId");

                    b.ToTable("users", null, t =>
                        {
                            t.HasCheckConstraint("ck_users_gender_allowed", "\"Gender\" IS NULL OR \"Gender\" IN ('male','female')");
                        });
                });

            modelBuilder.Entity("LdprActivistDemo.Persistence.UserPointsTransaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Amount")
                        .HasColumnType("integer");

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("TransactionAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "TransactionAt");

                    b.ToTable("user_points_transactions", (string)null);
                });

            modelBuilder.Entity("LdprActivistDemo.Persistence.City", b =>
                {
                    b.HasOne("LdprActivistDemo.Persistence.Region", "Region")
                        .WithMany("Cities")
                        .HasForeignKey("RegionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Region");
                });

            modelBuilder.Entity("LdprActivistDemo.Persistence.TaskEntity", b =>
                {
                    b.HasOne("LdprActivistDemo.Persistence.User", "AuthorUser")
                        .WithMany()
                        .HasForeignKey("AuthorUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LdprActivistDemo.Persistence.City", "City")
                        .WithMany()
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("LdprActivistDemo.Persistence.ImageEntity", null)
                        .WithMany()
                        .HasForeignKey("CoverImageId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("LdprActivistDemo.Persistence.Region", "Region")
                        .WithMany()
                        .HasForeignKey("RegionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AuthorUser");

                    b.Navigation("City");

                    b.Navigation("Region");
                });

            modelBuilder.Entity("LdprActivistDemo.Persistence.TaskSubmission", b =>
                {
                    b.HasOne("LdprActivistDemo.Persistence.User", "DecidedByAdmin")
                        .WithMany()
                        .HasForeignKey("DecidedByAdminId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("LdprActivistDemo.Persistence.TaskEntity", "Task")
                        .WithMany()
                        .HasForeignKey("TaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LdprActivistDemo.Persistence.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DecidedByAdmin");

                    b.Navigation("Task");

                    b.Navigation("User");
                });

            modelBuilder.Entity("LdprActivistDemo.Persistence.TaskSubmissionImage", b =>
                {
                    b.HasOne("LdprActivistDemo.Persistence.ImageEntity", "Image")
                        .WithMany()
                        .HasForeignKey("ImageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LdprActivistDemo.Persistence.TaskSubmission", "Submission")
                        .WithMany("PhotoImages")
                        .HasForeignKey("SubmissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Image");

                    b.Navigation("Submission");
                });

            modelBuilder.Entity("LdprActivistDemo.Persistence.TaskTrustedAdmin", b =>
                {
                    b.HasOne("LdprActivistDemo.Persistence.User", "AdminUser")
                        .WithMany()
                        .HasForeignKey("AdminUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LdprActivistDemo.Persistence.TaskEntity", "Task")
                        .WithMany("TrustedAdmins")
                        .HasForeignKey("TaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AdminUser");

                    b.Navigation("Task");
                });

            modelBuilder.Entity("LdprActivistDemo.Persistence.User", b =>
                {
                    b.HasOne("LdprActivistDemo.Persistence.City", "City")
                        .WithMany()
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LdprActivistDemo.Persistence.Region", "Region")
                        .WithMany()
                        .HasForeignKey("RegionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("City");

                    b.Navigation("Region");
                });

            modelBuilder.Entity("LdprActivistDemo.Persistence.UserPointsTransaction", b =>
                {
                    b.HasOne("LdprActivistDemo.Persistence.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("LdprActivistDemo.Persistence.Region", b =>
                {
                    b.Navigation("Cities");
                });

            modelBuilder.Entity("LdprActivistDemo.Persistence.TaskEntity", b =>
                {
                    b.Navigation("TrustedAdmins");
                });

            modelBuilder.Entity("LdprActivistDemo.Persistence.TaskSubmission", b =>
                {
                    b.Navigation("PhotoImages");
                });
#pragma warning restore 612, 618
        }
    }
}
