// <auto-generated />
using System;
using LdprActivistDemo.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace LdprActivistDemo.Migrations.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260325133613_ExtendFirstLoginTaskRulesConstraintWithEmptyDeadline")]
    partial class ExtendFirstLoginTaskRulesConstraintWithEmptyDeadline
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("LdprActivistDemo.Persistence.ImageEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<byte[]>("Data")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<Guid>("OwnerUserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("OwnerUserId");

                    b.ToTable("images", (string)null);
                });

            modelBuilder.Entity("LdprActivistDemo.Persistence.Region", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("regions", (string)null);
                });

            modelBuilder.Entity("LdprActivistDemo.Persistence.Settlement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("RegionId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("RegionId", "Name")
                        .IsUnique();

                    b.ToTable("settlements", (string)null);
                });

            modelBuilder.Entity("LdprActivistDemo.Persistence.SystemImageEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ImageId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ImageId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("system_images", (string)null);
                });

            modelBuilder.Entity("LdprActivistDemo.Persistence.TaskEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AuthorUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("AutoVerificationActionType")
                        .HasColumnType("text");

                    b.Property<Guid?>("CoverImageId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("DeadlineAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ExecutionLocation")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("PublishedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("RegionId")
                        .HasColumnType("integer");

                    b.Property<string>("RequirementsText")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ReuseType")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("disposable");

                    b.Property<int>("RewardPoints")
                        .HasColumnType("integer");

                    b.Property<int?>("SettlementId")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("VerificationType")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("manual");

                    b.HasKey("Id");

                    b.HasIndex("AuthorUserId");

                    b.HasIndex("CoverImageId");

                    b.HasIndex("SettlementId");

                    b.HasIndex("RegionId", "SettlementId", "Status", "DeadlineAt");

                    b.ToTable("tasks", null, t =>
                        {
                            t.HasCheckConstraint("ck_tasks_auto_verification_action_type_allowed", "(\"VerificationType\" = 'manual' AND \"AutoVerificationActionType\" IS NULL) OR (\"VerificationType\" = 'auto' AND \"AutoVerificationActionType\" IN ('invite_friend','first_login','auto'))");

                            t.HasCheckConstraint("ck_tasks_first_login_requires_auto_disposable", "\"AutoVerificationActionType\" IS NULL OR \"AutoVerificationActionType\" <> 'first_login' OR (\"VerificationType\" = 'auto' AND \"ReuseType\" = 'disposable' AND \"DeadlineAt\" IS NULL)");

                            t.HasCheckConstraint("ck_tasks_reuse_type_allowed", "\"ReuseType\" IN ('disposable','reusable')");

                            t.HasCheckConstraint("ck_tasks_reward_non_negative", "\"RewardPoints\" >= 0");

                            t.HasCheckConstraint("ck_tasks_status_allowed", "\"Status\" IN ('open','closed')");

                            t.HasCheckConstraint("ck_tasks_verification_type_allowed", "\"VerificationType\" IN ('auto','manual')");
                        });
                });

            modelBuilder.Entity("LdprActivistDemo.Persistence.TaskSubmission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("DecidedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("DecidedByCoordinatorId")
                        .HasColumnType("uuid");

                    b.Property<string>("DecisionStatus")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("in_progress");

                    b.Property<string>("ProofText")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("SubmittedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("TaskId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("DecidedByCoordinatorId");

                    b.HasIndex("UserId");

                    b.HasIndex("TaskId", "UserId");

                    b.ToTable("task_submissions", null, t =>
                        {
                            t.HasCheckConstraint("ck_task_submissions_decision_status_allowed", "\"DecisionStatus\" IN ('in_progress','submitted_for_review','approve','rejected')");
                        });
                });

            modelBuilder.Entity("LdprActivistDemo.Persistence.TaskSubmissionImage", b =>
                {
                    b.Property<Guid>("SubmissionId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ImageId")
                        .HasColumnType("uuid");

                    b.HasKey("SubmissionId", "ImageId");

                    b.HasIndex("ImageId");

                    b.ToTable("task_submission_images", (string)null);
                });

            modelBuilder.Entity("LdprActivistDemo.Persistence.TaskTrustedCoordinator", b =>
                {
                    b.Property<Guid>("TaskId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CoordinatorUserId")
                        .HasColumnType("uuid");

                    b.HasKey("TaskId", "CoordinatorUserId");

                    b.HasIndex("CoordinatorUserId");

                    b.ToTable("task_trusted_coordinators", (string)null);
                });

            modelBuilder.Entity("LdprActivistDemo.Persistence.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AvatarImageUrl")
                        .HasColumnType("text");

                    b.Property<DateOnly>("BirthDate")
                        .HasColumnType("date");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Gender")
                        .HasColumnType("text");

                    b.Property<bool>("IsPhoneConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("MiddleName")
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("RegionId")
                        .HasColumnType("integer");

                    b.Property<string>("Role")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("activist");

                    b.Property<int>("SettlementId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PhoneNumber")
                        .IsUnique();

                    b.HasIndex("RegionId");

                    b.HasIndex("SettlementId");

                    b.ToTable("users", null, t =>
                        {
                            t.HasCheckConstraint("ck_users_gender_allowed", "\"Gender\" IS NULL OR \"Gender\" IN ('male','female')");

                            t.HasCheckConstraint("ck_users_role_allowed", "\"Role\" IN ('activist','coordinator','admin','banned')");
                        });
                });

            modelBuilder.Entity("LdprActivistDemo.Persistence.UserPointsTransaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Amount")
                        .HasColumnType("integer");

                    b.Property<string>("CancellationComment")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("");

                    b.Property<DateTimeOffset?>("CancelledAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CancelledByAdminUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("CoordinatorUserId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsCancelled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<Guid?>("TaskId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("TransactionAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CancelledByAdminUserId");

                    b.HasIndex("CoordinatorUserId");

                    b.HasIndex("TaskId");

                    b.HasIndex("UserId", "TransactionAt");

                    b.ToTable("user_points_transactions", null, t =>
                        {
                            t.HasCheckConstraint("ck_user_points_transactions_cancel_state", "(\"IsCancelled\" = FALSE AND \"CancellationComment\" = '' AND \"CancelledAtUtc\" IS NULL AND \"CancelledByAdminUserId\" IS NULL) OR (\"IsCancelled\" = TRUE AND length(btrim(\"CancellationComment\")) > 0 AND \"CancelledAtUtc\" IS NOT NULL AND \"CancelledByAdminUserId\" IS NOT NULL)");
                        });
                });

            modelBuilder.Entity("LdprActivistDemo.Persistence.UserRating", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<int?>("OverallRank")
                        .HasColumnType("integer");

                    b.Property<int?>("RegionRank")
                        .HasColumnType("integer");

                    b.Property<int?>("SettlementRank")
                        .HasColumnType("integer");

                    b.HasKey("UserId");

                    b.ToTable("user_ratings", (string)null);
                });

            modelBuilder.Entity("LdprActivistDemo.Persistence.UserRatingsRefreshState", b =>
                {
                    b.Property<string>("JobName")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("LastCompletedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly?>("LastCompletedLocalDate")
                        .HasColumnType("date");

                    b.Property<int>("ScheduledHour")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(4);

                    b.Property<int>("ScheduledMinute")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.HasKey("JobName");

                    b.ToTable("user_ratings_refresh_state", null, t =>
                        {
                            t.HasCheckConstraint("ck_user_ratings_refresh_state_hour_range", "\"ScheduledHour\" >= 0 AND \"ScheduledHour\" <= 23");

                            t.HasCheckConstraint("ck_user_ratings_refresh_state_minute_range", "\"ScheduledMinute\" >= 0 AND \"ScheduledMinute\" <= 59");
                        });
                });

            modelBuilder.Entity("LdprActivistDemo.Persistence.ImageEntity", b =>
                {
                    b.HasOne("LdprActivistDemo.Persistence.User", "OwnerUser")
                        .WithMany("OwnedImages")
                        .HasForeignKey("OwnerUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OwnerUser");
                });

            modelBuilder.Entity("LdprActivistDemo.Persistence.Settlement", b =>
                {
                    b.HasOne("LdprActivistDemo.Persistence.Region", "Region")
                        .WithMany("Settlements")
                        .HasForeignKey("RegionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Region");
                });

            modelBuilder.Entity("LdprActivistDemo.Persistence.SystemImageEntity", b =>
                {
                    b.HasOne("LdprActivistDemo.Persistence.ImageEntity", "Image")
                        .WithMany()
                        .HasForeignKey("ImageId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Image");
                });

            modelBuilder.Entity("LdprActivistDemo.Persistence.TaskEntity", b =>
                {
                    b.HasOne("LdprActivistDemo.Persistence.User", "AuthorUser")
                        .WithMany()
                        .HasForeignKey("AuthorUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LdprActivistDemo.Persistence.ImageEntity", null)
                        .WithMany()
                        .HasForeignKey("CoverImageId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("LdprActivistDemo.Persistence.Region", "Region")
                        .WithMany()
                        .HasForeignKey("RegionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LdprActivistDemo.Persistence.Settlement", "Settlement")
                        .WithMany()
                        .HasForeignKey("SettlementId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("AuthorUser");

                    b.Navigation("Region");

                    b.Navigation("Settlement");
                });

            modelBuilder.Entity("LdprActivistDemo.Persistence.TaskSubmission", b =>
                {
                    b.HasOne("LdprActivistDemo.Persistence.User", "DecidedByCoordinator")
                        .WithMany()
                        .HasForeignKey("DecidedByCoordinatorId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("LdprActivistDemo.Persistence.TaskEntity", "Task")
                        .WithMany()
                        .HasForeignKey("TaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LdprActivistDemo.Persistence.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DecidedByCoordinator");

                    b.Navigation("Task");

                    b.Navigation("User");
                });

            modelBuilder.Entity("LdprActivistDemo.Persistence.TaskSubmissionImage", b =>
                {
                    b.HasOne("LdprActivistDemo.Persistence.ImageEntity", "Image")
                        .WithMany()
                        .HasForeignKey("ImageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LdprActivistDemo.Persistence.TaskSubmission", "Submission")
                        .WithMany("PhotoImages")
                        .HasForeignKey("SubmissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Image");

                    b.Navigation("Submission");
                });

            modelBuilder.Entity("LdprActivistDemo.Persistence.TaskTrustedCoordinator", b =>
                {
                    b.HasOne("LdprActivistDemo.Persistence.User", "CoordinatorUser")
                        .WithMany()
                        .HasForeignKey("CoordinatorUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LdprActivistDemo.Persistence.TaskEntity", "Task")
                        .WithMany("TrustedCoordinators")
                        .HasForeignKey("TaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CoordinatorUser");

                    b.Navigation("Task");
                });

            modelBuilder.Entity("LdprActivistDemo.Persistence.User", b =>
                {
                    b.HasOne("LdprActivistDemo.Persistence.Region", "Region")
                        .WithMany()
                        .HasForeignKey("RegionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LdprActivistDemo.Persistence.Settlement", "Settlement")
                        .WithMany()
                        .HasForeignKey("SettlementId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Region");

                    b.Navigation("Settlement");
                });

            modelBuilder.Entity("LdprActivistDemo.Persistence.UserPointsTransaction", b =>
                {
                    b.HasOne("LdprActivistDemo.Persistence.User", "CancelledByAdminUser")
                        .WithMany()
                        .HasForeignKey("CancelledByAdminUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("LdprActivistDemo.Persistence.User", "CoordinatorUser")
                        .WithMany()
                        .HasForeignKey("CoordinatorUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("LdprActivistDemo.Persistence.TaskEntity", "Task")
                        .WithMany()
                        .HasForeignKey("TaskId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("LdprActivistDemo.Persistence.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CancelledByAdminUser");

                    b.Navigation("CoordinatorUser");

                    b.Navigation("Task");

                    b.Navigation("User");
                });

            modelBuilder.Entity("LdprActivistDemo.Persistence.UserRating", b =>
                {
                    b.HasOne("LdprActivistDemo.Persistence.User", "User")
                        .WithOne()
                        .HasForeignKey("LdprActivistDemo.Persistence.UserRating", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("LdprActivistDemo.Persistence.Region", b =>
                {
                    b.Navigation("Settlements");
                });

            modelBuilder.Entity("LdprActivistDemo.Persistence.TaskEntity", b =>
                {
                    b.Navigation("TrustedCoordinators");
                });

            modelBuilder.Entity("LdprActivistDemo.Persistence.TaskSubmission", b =>
                {
                    b.Navigation("PhotoImages");
                });

            modelBuilder.Entity("LdprActivistDemo.Persistence.User", b =>
                {
                    b.Navigation("OwnedImages");
                });
#pragma warning restore 612, 618
        }
    }
}
